import React, { useState, useEffect, useRef } from "react";
import { supabase, getActiveListings, createListing, createOrder, getVendorSales, upsertVendor, getVendor, getAdsFromDB, updateAdInDB } from "./supabase";
import { motion, AnimatePresence } from "motion/react";

// ─── TRANSLATIONS ────────────────────────────────────────────────────────────
const T = {
  en: {
    appTagline:"Vendor Portal", buy:"Deals", sell:"Sell", studentTab:"🎓 Students",
    searchPlaceholder:"Search food or shops...",
    halalAny:"Halal", halalCert:"Certified", muslimOwned:"Muslim-Owned", all:"All", allCat:"All",
    nearbyDeals:"Deals Near You", searchResults:"Search Results ({0})",
    almostGone:"Almost Gone", item:"item",
    save:"SAVE", perUnit:"unit left", soldOut:"Sold Out",
    surplusTag:"🔥 Limited Deal", promoTag:"⚡ Flash Deal", specialTag:"🌟 Special",
    studentTag:"🎓 Student Deal",
    microwave:"♨️ Microwave", addToCart:"Add to Cart", addedToCart:"✅ Added",
    expired:"Expired", justNow:"Just now", minAgo:"min ago", hrAgo:"hr ago",
    noDeals:"No deals found", tryFilter:"Try a different filter or search",
    halalCertLabel:"Halal Cert", muslimOwnedLabel:"Muslim-Owned", nonHalalLabel:"Non-Halal",
    halalSelfDeclared:"*Halal status is self-declared by vendors",
    almostOut:"Almost out —", unitsLeft:"units left", soldOutLabel:"Sold Out 🎉",
    endsAt:"Until", units:"units", back:"← Back",
    freeDeliveryFrom:"🚗 Free delivery from RM{0}",
    noDelivery:"Self-pickup only",
    halalDisclaimerTitle:"Halal Status Notice",
    halalDisclaimerBody:"The Halal and Muslim-Owned badges are self-declared by vendors. Sapot Lokal does not check or guarantee any halal status.\n\nPlease use your own judgement. Sapot Lokal is not responsible for any halal claims.",
    halalDisclaimerBtn:"I understand, continue",
    studentCornerTitle:"🎓 Student Corner",
    studentCornerDesc:"Special prices posted by vendors who support students. No verification needed.",
    studentCornerEmpty:"No student deals right now",
    studentCornerEmptySub:"Check back later — vendors post new student deals throughout the day.",
    studentPriceLabel:"Student price",
    cart:"Cart", cartEmpty:"Your cart is empty", browseDeals:"Browse deals above",
    subtotal:"Subtotal", deliveryFee:"Delivery Fee",
    free:"FREE", total:"Total",
    selfPickup:"Self-Pickup", selfPickupDesc:"Walk over and collect (Free)",
    delivery:"Delivery", deliveryDesc:"Delivered to your door",
    checkoutTNG:"💙 Pay with TNG eWallet",
    processingTNG:"Processing...",
    removeItem:"Remove",
    orderPlaced:"Order Confirmed!", pickupNote:"Show this code to the vendor",
    pickupCode:"Pickup Code", goPickup:"Got it!",
    whatToPost:"What to post today?", chooseType:"Pick a deal type",
    surplusType:"🔥 Limited Deal", surplusDesc:"Discounted food — limited quantity",
    promoType:"⚡ Flash Deal", promoDesc:"Time-limited offer",
    specialType:"🌟 Special", specialDesc:"New dish — get feedback",
    chooseCategory:"Choose Category", templateNote:"Template fills in basic info",
    postNewDeal:"Post a Deal", liveNow:"Live Now", repeatBtn:"Repeat", activeLabel:"Active",
    snapPhoto:"Take Food Photo", retakePhoto:"Retake", uploading:"Uploading...", snapFirst2:"Take a photo",
    foodName:"Food Name", foodNamePH:"e.g. Nasi Lemak",
    shortDesc:"Description", shortDescPH:"e.g. Egg, Sambal, Anchovies",
    originalPrice:"Original Price (RM)", dealPrice:"Deal Price (RM)",
    youReceive:"You get (after fees)",
    endTime:"End Time", quick:"⚡ Quick", manual:"🕐 Manual", endAt:"Ends at:",
    qty:"Quantity (Optional)", qtyPH:"e.g. 20", qtyNote:"Leave empty for unlimited",
    reheat:"How to reheat", eatDirect:"🍽️ Ready to eat", oven:"🔥 Oven",
    goLive:"⚡ Go Live", snapFirst:"📸 Take Photo First",
    fillName:"✏️ Add Food Name", fillPrice:"💰 Add Deal Price",
    tngNote:"Payments handled via TNG eWallet",
    pastPosts:"Past Posts", repostNote:"Tap to repost",
    repost:"🔁 Repost", sold:"sold",
    postSuccess:"Posted!", liveNote:"Your deal is live. Nearby buyers will be notified.",
    salePrice:"Sale Price", commission:"Sapot Fee",
    youGet:"You Receive", payoutNote:"Paid to your TNG after pickup",
    viewDash:"View Dashboard",
    addStudentPrice:"Add Student Price?",
    addStudentPriceDesc:"Show a lower price in Student Corner",
    studentPriceRM:"Student Price (RM)",
    studentPricePH:"e.g. 2.50",
    vendorSettings:"Shop Settings",
    freeDeliveryThreshold:"Free Delivery Min (RM)",
    thresholdOff:"No free delivery",
    thresholdWarning:"~RM8 delivery cost deducted from your payout",
    saveSettings:"Save", settingsSaved:"✅ Saved",
    offerFreeDelivery:"Offer free delivery",
    monthlyPlan:"Monthly Plan", perMonth:"/mo",
    subscribeCTA:"💙 Subscribe via TNG", autoRenew:"Auto-renews · Cancel anytime",
    processing:"Processing...",
    timeModeLabel:"How long to show?",
    timeModeStock:"⏳ While stock lasts",
    timeModeStock_desc:"Live until sold out or removed",
    timeModeHours:"⚡ Fixed time",
    timeModeHours_desc:"Auto-removes after set hours",
    timeModeSched:"🕐 Today's hours",
    timeModeSched_desc:"Live from open to close",
    openTime:"Opens at", closeTime:"Closes at",
    liveUntil:"Live until",
    liveUntilStock:"Live · Until sold out",
    liveUntilClose:"Live · Until closing",
    removePost:"✕ Remove",
    cancelConfirm:"Remove this post?",
    cancelYes:"Yes, remove",
    cancelNo:"Keep it live",
    trialActive:"Free Trial",
    trialDaysLeft:"{0} days left",
    trialExpired:"Free trial ended",
    trialExpiredDesc:"Subscribe to keep posting deals.",
    trialBannerFree:"🎁 Free for {0} more days",
    trialBannerWarn:"⚠️ {0} days left in trial",
    trialBannerUrgent:"🔴 Trial ends in {0} days!",
    trialBannerExpired:"🔒 Trial ended — subscribe to post",
    subscribeNow:"Subscribe Now",
    alreadySubscribed:"✅ Active plan",
    subscribedUntil:"Active until {0}",
    maxPostsReached:"Max 3 active posts — remove one first",
    onboardTitle:"Set Up Your Shop",
    onboardSub:"Takes 30 seconds.",
    onboardShopName:"Shop Name",
    onboardShopNamePH:"e.g. Warung Mak Teh",
    onboardArea:"Your Area",
    onboardAreaPH:"e.g. Puchong, Subang",
    onboardPhone:"WhatsApp Number",
    onboardPhonePH:"e.g. 0123456789",
    onboardDone:"Start Selling →",
    onboardSkip:"Skip for now",
    locating:"Finding your location...",
    locationDenied:"Where are you? 📍",
    locationDeniedDesc:"Type your area to see nearby food deals",
    nearYou:"Near You",
    kmAway:"{0}km away",
    noDealsArea:"No deals near you right now",
    noDealsAreaSub:"Vendors in {0} haven't posted yet. Check back soon!",
    changeLocation:"Change location",
    orderingFrom:"Ordering from",
    differentVendorTitle:"Start a new order?",
    differentVendorBody:"You already have items from {0} in your cart. Adding from {1} needs a separate order.",
    clearCartBtn:"Start new order",
    keepCartBtn:"Keep current cart",
    continueShoppingBtn:"Add more from {0}",
    vendorLockedMsg:"Finish your current order first",
    planBasic:"Basic", planPro:"Pro", planBusiness:"Business", planPopular:"Most Popular",
    planBasicDesc:"For new vendors just starting out",
    planProDesc:"For active vendors growing fast",
    planBusinessDesc:"For high-volume food businesses",
    planBasicPerks:["Post up to 3 deals","15% commission","Basic dashboard","Student corner listings"],
    planProPerks:["Post up to 10 deals","10% commission","Full dashboard","Priority buyer alerts","One-tap repost","Free delivery settings"],
    planBusinessPerks:["Unlimited posts","8% commission","Advanced analytics","Dedicated support","Custom storefront","API access"],
    choosePlan:"Choose Your Plan",
    choosePlanSub:"Start free for 60 days, then subscribe",
    currentPlan:"Current Plan",
    upgradePlan:"Upgrade",
    celebTitle:"Welcome aboard! 🎉",
    celebSub:"Your {0} plan is now active.",
    celebBtn:"Start Posting",
    catAll:"All Deals", catFood:"Food", catDrink:"Drink", catFruit:"Fruit", catBakery:"Bakery", catOther:"Other",
    shareTitle:"Share Deal", shareWhatsapp:"Share on WhatsApp", shareCopy:"Copy Link", shareCopied:"Link Copied!",
    shareMsg:"🍱 Check out this deal at Sapot Lokal: {0} from {1} for only RM{2}! 👉 {3}",
  },
  bm: {
    appTagline:"Portal Vendor", buy:"Deal", sell:"Jual", studentTab:"🎓 Pelajar",
    searchPlaceholder:"Cari makanan atau kedai...",
    halalAny:"Halal", halalCert:"Bertauliah", muslimOwned:"Milik Muslim", all:"Semua", allCat:"Semua",
    nearbyDeals:"Deal Berdekatan", searchResults:"Hasil Carian ({0})",
    almostGone:"Hampir Habis", item:"item",
    save:"JIMAT", perUnit:"unit tinggal", soldOut:"Sold Out",
    surplusTag:"🔥 Limited Deal", promoTag:"⚡ Flash Deal", specialTag:"🌟 Menu Baru",
    studentTag:"🎓 Harga Pelajar",
    microwave:"♨️ Microwave", addToCart:"Tambah ke Troli", addedToCart:"✅ Ditambah",
    expired:"Tamat", justNow:"Baru sahaja", minAgo:"min lalu", hrAgo:"jam lalu",
    noDeals:"Tiada deal dijumpai", tryFilter:"Cuba tukar filter atau cari semula",
    halalCertLabel:"Halal Cert", muslimOwnedLabel:"Milik Muslim", nonHalalLabel:"Non-Halal",
    halalSelfDeclared:"*Diisytihar sendiri oleh vendor",
    almostOut:"Hampir habis —", unitsLeft:"unit", soldOutLabel:"Habis Terjual 🎉",
    endsAt:"Hingga", units:"unit", back:"← Kembali",
    freeDeliveryFrom:"🚗 Penghantaran percuma dari RM{0}",
    noDelivery:"Ambil sendiri sahaja",
    halalDisclaimerTitle:"Notis Status Halal",
    halalDisclaimerBody:"Lencana Halal dan Milik Muslim dalam app ini adalah pengisytiharan sendiri oleh vendor. Sapot Lokal tidak mengesahkan atau menjamin status halal mana-mana makanan.\n\nPembeli dinasihatkan untuk membuat pertimbangan sendiri. Sapot Lokal tidak bertanggungjawab ke atas status halal.",
    halalDisclaimerBtn:"Saya faham, teruskan",
    studentCornerTitle:"🎓 Sudut Pelajar",
    studentCornerDesc:"Harga khas yang dipost oleh vendor yang menyokong pelajar kampus. Tiada pengesahan diperlukan.",
    studentCornerEmpty:"Tiada deal pelajar buat masa ini",
    studentCornerEmptySub:"Vendor post deal pelajar baru sepanjang hari. Semak semula nanti!",
    studentPriceLabel:"Harga pelajar",
    cart:"Troli", cartEmpty:"Troli anda kosong", browseDeals:"Semak deal di atas",
    subtotal:"Subtotal", deliveryFee:"Yuran Penghantaran",
    free:"PERCUMA", total:"Jumlah",
    selfPickup:"Ambil Sendiri", selfPickupDesc:"Jalan ambil sendiri (Percuma)",
    delivery:"Penghantaran", deliveryDesc:"Dihantar ke pintu anda",
    checkoutTNG:"💙 Bayar via TNG eWallet",
    processingTNG:"Memproses...",
    removeItem:"Buang",
    orderPlaced:"Pesanan Berjaya!", pickupNote:"Tunjukkan kod ini kepada vendor",
    pickupCode:"Kod Pickup", goPickup:"Okay, Faham!",
    whatToPost:"Apa nak post hari ni?", chooseType:"Pilih jenis deal anda",
    surplusType:"🔥 Limited Deal", surplusDesc:"Makanan lebihan — kuantiti terhad",
    promoType:"⚡ Flash Deal", promoDesc:"Tawaran masa terhad",
    specialType:"🌟 Menu Baru", specialDesc:"Lancar hidangan baru — dapat feedback",
    chooseCategory:"Pilih Kategori", templateNote:"Template isi maklumat asas",
    postNewDeal:"Post Deal Baru", liveNow:"Live Sekarang", repeatBtn:"Ulang", activeLabel:"Aktif",
    snapPhoto:"Snap Gambar Makanan", retakePhoto:"Tukar Gambar", uploading:"Memuat...", snapFirst2:"Snap gambar makanan",
    foodName:"Nama Makanan", foodNamePH:"cth: Nasi Lemak Bungkus",
    shortDesc:"Huraian Ringkas", shortDescPH:"cth: Telur, Sambal, Ikan Bilis",
    originalPrice:"Harga Asal (RM)", dealPrice:"Harga Deal (RM)",
    youReceive:"Anda terima (selepas fi)",
    endTime:"Masa Tamat", quick:"⚡ Pantas", manual:"🕐 Manual", endAt:"Tamat pada:",
    qty:"Kuantiti (Pilihan)", qtyPH:"cth: 20 unit", qtyNote:"Kosongkan untuk tiada had",
    reheat:"Cara Panaskan Semula", eatDirect:"🍽️ Terus", oven:"🔥 Oven",
    goLive:"⚡ Go Live Sekarang", snapFirst:"📸 Snap Gambar Dahulu",
    fillName:"✏️ Isi Nama", fillPrice:"💰 Isi Harga",
    tngNote:"Bayaran diproses melalui TNG eWallet",
    pastPosts:"Posting Lepas", repostNote:"Tap untuk repost serta-merta",
    repost:"🔁 Repost", sold:"dijual",
    postSuccess:"Posting Berjaya!", liveNote:"Deal anda live. Pembeli berdekatan akan dimaklumkan.",
    salePrice:"Harga Jual", commission:"Fi Sapot",
    youGet:"Anda Terima", payoutNote:"Dibayar ke TNG selepas pickup",
    viewDash:"Lihat Dashboard",
    addStudentPrice:"Tambah Harga Pelajar?",
    addStudentPriceDesc:"Paparkan harga lebih rendah dalam Sudut Pelajar",
    studentPriceRM:"Harga Pelajar (RM)", studentPricePH:"cth: 2.50",
    vendorSettings:"Tetapan Kedai",
    freeDeliveryThreshold:"Had Penghantaran Percuma (RM)",
    thresholdOff:"Tiada penghantaran percuma",
    thresholdWarning:"~RM8 kos penghantaran ditolak dari bayaran anda",
    saveSettings:"Simpan", settingsSaved:"✅ Disimpan",
    offerFreeDelivery:"Tawarkan penghantaran percuma",
    monthlyPlan:"Pelan Bulanan", perMonth:"/bulan",
    subscribeCTA:"💙 Langgan via TNG", autoRenew:"Auto-renew · Batal bila-bila masa",
    processing:"Memproses...",
    timeModeLabel:"Berapa lama posting ini kekal?",
    timeModeStock:"⏳ Selagi ada stok", timeModeStock_desc:"Kekal live sehingga habis atau anda buang",
    timeModeHours:"⚡ Tempoh tetap", timeModeHours_desc:"Auto-buang selepas jam yang ditetapkan",
    timeModeSched:"🕐 Jadual hari ini", timeModeSched_desc:"Live dari buka hingga tutup kedai",
    openTime:"Buka jam", closeTime:"Tutup jam",
    liveUntil:"Live sehingga", liveUntilStock:"Live · Selagi ada stok", liveUntilClose:"Live · Hingga waktu tutup",
    removePost:"✕ Buang", cancelConfirm:"Buang listing ini?", cancelYes:"Ya, buang", cancelNo:"Kekalkan live",
    trialActive:"Percubaan Percuma", trialDaysLeft:"{0} hari lagi",
    trialExpired:"Percubaan percuma tamat", trialExpiredDesc:"Langgan untuk terus posting deal.",
    trialBannerFree:"🎁 Percuma {0} hari lagi", trialBannerWarn:"⚠️ {0} hari lagi dalam percubaan",
    trialBannerUrgent:"🔴 Percubaan tamat dalam {0} hari!", trialBannerExpired:"🔒 Percubaan tamat — langgan untuk post",
    subscribeNow:"Langgan Sekarang", alreadySubscribed:"✅ Langganan aktif", subscribedUntil:"Dilanggan hingga {0}",
    maxPostsReached:"Maks 3 posting aktif — buang satu untuk post semula",
    onboardTitle:"Sediakan Kedai Anda", onboardSub:"Ambil masa 30 saat.",
    onboardShopName:"Nama Kedai", onboardShopNamePH:"cth: Warung Mak Teh",
    onboardArea:"Kawasan / Bandar Anda", onboardAreaPH:"cth: Puchong, Kepong",
    onboardPhone:"Nombor WhatsApp", onboardPhonePH:"cth: 0123456789",
    onboardDone:"Mula Jual →", onboardSkip:"Langkau buat masa ini",
    locating:"Mencari lokasi anda...", locationDenied:"Di mana anda? 📍",
    locationDeniedDesc:"Taip kawasan anda untuk melihat deal berdekatan",